name: Conjur Auth Test

on:
  workflow_call:

    inputs:

      host-id:
        required: true
        type: string

    outputs:

      conjur-token:
        value: ${{ jobs.auth.outputs.conjur-token }}

jobs:

  auth:

    runs-on: ubuntu-latest

    outputs:
      conjur-token: ${{ steps.auth.outputs.conjur-token }}

    steps:

      - name: Authenticate to Conjur
        id: auth

        env:
          EDGE: https://csas-sandbox.secretsmgr.cyberark.cloud
          API_KEY: ${{ secrets.CONJUR_APIKEY }}

        run: |

          HOST_ID="${{ inputs.host-id }}"

          LOGIN_ENC="host%2F$(echo "$HOST_ID" | sed 's|/|%2F|g')"

          TOKEN=$(curl -sk \
            --request POST \
            "$EDGE/api/authn/conjur/$LOGIN_ENC/authenticate" \
            --header "Content-Type: application/json" \
            --header "Accept-Encoding: base64" \
            --data "$API_KEY")

          echo "Token Length: ${#TOKEN}"

          echo "conjur-token=$TOKEN" >> $GITHUB_OUTPUT
