name: Create Conjur Variable

on:

  workflow_call:

    inputs:

      policy-path:
        required: true
        type: string

      variable-name:
        required: true
        type: string

      conjur-token:
        required: true
        type: string

jobs:

  create-variable:

    runs-on: ubuntu-latest

    steps:

      - name: Generate Policy File

        run: |

          cat > variable.yml <<EOF
          - !variable ${{ inputs.variable-name }}

          - !permit
            resource: !variable ${{ inputs.variable-name }}
            privileges: [ read, execute, update ]
            role: !group write
          EOF

          echo "Generated policy:"
          cat variable.yml

      - name: Update Policy

        env:
          EDGE: https://TVUJ-CLOUD-ENDPOINT

        run: |

          POLICY_ID="${{ inputs.policy-path }}"

          POLICY_ENC=$(printf '%s' "$POLICY_ID" | sed 's|/|%2F|g')

          curl -sk \
            -X PATCH \
            -H "Authorization: Token token=${{ inputs.conjur-token }}" \
            -H "Content-Type: application/yaml" \
            --data-binary @variable.yml \
            "$EDGE/api/policies/conjur/policy/$POLICY_ENC"
