name: Set Conjur Secret

on:

  workflow_call:

    inputs:

      variable-path:
        required: true
        type: string

      secret-value:
        required: true
        type: string

      conjur-token:
        required: true
        type: string

jobs:

  set-secret:

    runs-on: ubuntu-latest

    steps:

      - name: Set Secret

        env:
          EDGE: https://TVUJ-CLOUD-ENDPOINT

        run: |

          VARIABLE_ID="${{ inputs.variable-path }}"

          VARIABLE_ENC=$(printf '%s' "$VARIABLE_ID" | sed 's|/|%2F|g')

          HTTP_CODE=$(curl -sk \
            -o response.txt \
            -w "%{http_code}" \
            -X POST \
            -H "Authorization: Token token=${{ inputs.conjur-token }}" \
            --data-binary "${{ inputs.secret-value }}" \
            "$EDGE/api/secrets/conjur/variable/$VARIABLE_ENC")

          echo "HTTP Status: $HTTP_CODE"

          if [ "$HTTP_CODE" != "204" ]; then
            echo "Secret update failed"
            cat response.txt
            exit 1
          fi

          echo "Secret updated successfully"
