name: Share Conjur Secret

on:

  workflow_dispatch:

    inputs:

      sas:
        description: "SAS Name (e.g. pim)"
        required: true
        type: string

      env:
        description: "Environment (dev/int/prs/pred/prod)"
        required: true
        type: string

      variable-name:
        description: "Variable Name"
        required: true
        type: string

      target-group:
        description: "Full Conjur Group Path"
        required: true
        type: string

jobs:

  auth:

    uses: ./.github/workflows/conjur-authn.yml

    with:
      host-id: data/workloads/${{ inputs.sas }}-${{ inputs.env }}
    secrets: inherit
      
  share:

    needs: auth

    runs-on: ubuntu-latest

    steps:

      - name: Calculate Paths
        id: calc

        run: |

          SAS="${{ inputs.sas }}"
          ENV="${{ inputs.env }}"

          POLICY_PATH="data/app_storage/$SAS/$SAS-$ENV"

          echo "policy-path=$POLICY_PATH" >> $GITHUB_OUTPUT

      - name: Generate Permit

        run: |

          cat > permit.yml <<EOF
          - !permit
            role: !group ${{ inputs.target-group }}
            privileges: [ read, execute ]
            resource: !variable ${{ inputs.variable-name }}
          EOF

          cat permit.yml

      - name: Share Variable

        env:
          EDGE: ${{ needs.auth.outputs.edge }}
          TOKEN: ${{ needs.auth.outputs.conjur-token }}

        run: |

          POLICY_ENC=$(printf '%s' "${{ steps.calc.outputs.policy-path }}" | sed 's|/|%2F|g')

          curl -sk \
            -X PATCH \
            -H "Authorization: Token token=$TOKEN" \
            -H "Content-Type: application/yaml" \
            --data-binary @permit.yml \
            "$EDGE/api/policies/conjur/policy/$POLICY_ENC"

      - name: Summary

        run: |

          echo "Variable:"
          echo "${{ inputs.variable-name }}"

          echo "Shared with:"
          echo "${{ inputs.target-group }}"
